[workspace]
authors = ["GuChangfeng <changfenggu81@gmail.com>"]
channels = ["conda-forge"]
name = "nrftest"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
just = "==1.58.0"

[target.win-64.dependencies]
python = "3.10.*"
pip = ">=26.2.1,<27"
pytest = ">=9.1.1,<10"

[target.win-64.pypi-dependencies]
blatann = "==0.6.0"
pc-ble-driver-py = "==0.17.0"
